name: Dispatch kubewarden image

on:
  push:
    branches: [kubewarden]
#     paths-ignore:
#       - ".github/workflows/**"
  pull_request:
    branches: [kubewarden]

jobs:
  build:
    name: Dispatch ui image
    runs-on: ubuntu-latest
    # outputs:
    #   repository: ghcr.io/kubewarden/UI
    #   tag: ${{ env.TAG_NAME }}
    #   artifact: kubewarden-ui-image-${{ env.TAG_NAME }}
    steps:
      - uses: actions/checkout@v2

      # Dispatch event to the branched repo
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
          repository: jordojordo/UI
          event-type: dispatch-ui
